# Generated by Django 6.0 on 2025-12-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SandboxPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pg_tid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="EasyPay transaction ID (pgTid)",
                        max_length=100,
                        verbose_name="PG 거래번호",
                    ),
                ),
                (
                    "authorization_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="EasyPay authorizationId from payment callback",
                        max_length=100,
                        verbose_name="인증번호",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Payment amount in KRW",
                        max_digits=10,
                        verbose_name="결제금액",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "결제대기"),
                            ("completed", "결제완료"),
                            ("failed", "결제실패"),
                            ("cancelled", "취소"),
                            ("refunded", "환불"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="결제상태",
                    ),
                ),
                (
                    "pay_method_type_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="EasyPay payMethodTypeCode (11=card, 21=bank, 31=phone)",
                        max_length=20,
                        verbose_name="결제수단",
                    ),
                ),
                (
                    "card_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Card issuer name",
                        max_length=50,
                        verbose_name="카드사",
                    ),
                ),
                (
                    "card_no",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Masked card number",
                        max_length=20,
                        verbose_name="카드번호",
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address at payment time",
                        null=True,
                        verbose_name="클라이언트 IP",
                    ),
                ),
                (
                    "client_user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Browser user agent string",
                        max_length=500,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="생성일시"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="결제일시"
                    ),
                ),
                (
                    "goods_name",
                    models.CharField(
                        default="테스트 상품",
                        help_text="Product name for EasyPay display",
                        max_length=100,
                        verbose_name="상품명",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique order identifier (auto-generated)",
                        max_length=50,
                        unique=True,
                        verbose_name="주문번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sandbox Payment",
                "verbose_name_plural": "Sandbox Payments",
                "db_table": "easypay_sandbox_payment",
            },
        ),
    ]
