# Generated by Django 6.0 on 2026-01-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hash_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="External-facing unique identifier for URLs (auto-generated)",
                        max_length=12,
                        unique=True,
                        verbose_name="해시 ID",
                    ),
                ),
                (
                    "pg_tid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="EasyPay transaction ID (pgTid)",
                        max_length=100,
                        verbose_name="PG 거래번호",
                    ),
                ),
                (
                    "authorization_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="EasyPay authorizationId from payment callback",
                        max_length=100,
                        verbose_name="인증번호",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Payment amount in KRW (total including tax)",
                        max_digits=10,
                        verbose_name="결제금액",
                    ),
                ),
                (
                    "supply_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Supply amount excluding VAT",
                        max_digits=10,
                        verbose_name="공급가액",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="VAT amount (10% of supply_amount for taxable)",
                        max_digits=10,
                        verbose_name="부가세액",
                    ),
                ),
                (
                    "tax_free_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Tax-free amount",
                        max_digits=10,
                        verbose_name="면세금액",
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=True,
                        help_text="True for taxable, False for tax-free transactions",
                        verbose_name="과세 여부",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "결제대기"),
                            ("completed", "결제완료"),
                            ("failed", "결제실패"),
                            ("cancelled", "취소"),
                            ("refunded", "환불"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="결제상태",
                    ),
                ),
                (
                    "pay_method_type_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="EasyPay payMethodTypeCode (11=card, 21=bank, 31=phone)",
                        max_length=20,
                        verbose_name="결제수단",
                    ),
                ),
                (
                    "card_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Card issuer name",
                        max_length=50,
                        verbose_name="카드사",
                    ),
                ),
                (
                    "card_no",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Masked card number",
                        max_length=20,
                        verbose_name="카드번호",
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address at payment time",
                        null=True,
                        verbose_name="클라이언트 IP",
                    ),
                ),
                (
                    "client_user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Browser user agent string",
                        max_length=500,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="생성일시"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="결제일시"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", help_text="Test payment description", max_length=200
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        help_text="External order identifier",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Payment",
                "verbose_name_plural": "Test Payments",
                "db_table": "tests_payment",
                "ordering": ["-created_at"],
            },
        ),
    ]
